libsepol/src/policydb.c

When reading policy, ibendport device names are allocated in
ocontext_read_selinux() but they are not freed when calling
sepol_policydb_free();
Fix this by freeing them in ocontext_selinux_free().
Signed-off-by: Jan Zarsky <jzarsky@redhat.com>

libsepol: free ibendport device names

---

.travis.yml

Some Travis-CI builds failed because of issues when downloading
refpolicy files for sepolgen tests. Use curl's option --retry to make
the downloads work when the networking issues are only transient.
Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>

Travis-CI: try working around network issues by retrying downloads

---

libsemanage/src/database_llist.c

Function dbase_llist_iterate iterates over records and checks return
value of iterate function. According to a manpage semanage_iterate(3),
handler can return value 1 for early exit. dbase_llist_iterate
currently checks for return value > 1, which does not include
expected value 1. This affects most of the semanage_*_iterate
and semanage_*_local functions.
Signed-off-by: Jan Zarsky <jzarsky@redhat.com>

libsemanage: properly check return value of iterate function

---

python/semanage/seobject.py

Commit 985753f changed behavior of seobject class constructors. While
semanage itself was fixed, there are other tools like
system-config-selinux and chcat which depend on the original behavior.
This change make the constructors backward compatible.
Fixes: $ system-config-selinux
Traceback (most recent call last):
File "/usr/share/system-config-selinux/system-config-selinux.py", line 196, in <module>
app = childWindow()
File "/usr/share/system-config-selinux/system-config-selinux.py", line 100, in __init__
self.add_page(booleansPage.booleansPage(xml))
File "/usr/share/system-config-selinux/booleansPage.py", line 142, in __init__
self.load(self.filter)
File "/usr/share/system-config-selinux/booleansPage.py", line 212, in load
self.booleans = seobject.booleanRecords()
TypeError: __init__() …

python/semanage: make seobject.py backward compatible

---

libselinux/man/man5/removable_context.5
libselinux/man/man5/selabel_media.5

The selabel_media(5) man page incorrectly stated that the
removable_context(5) would be read if an selabel_lookup(3)
failed. Correct the man pages that fixes [1].
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1395621
Signed-off-by: Richard Haines <richard_c_haines@btinternet.com>

libselinux: Correct manpages regarding removable_context

---

libsemanage/src/direct_api.c
libsemanage/src/handle.c
libsemanage/src/handle.h

Allow the tmp build files to be kept for debugging when a policy
build fails.
Signed-off-by: Richard Haines <richard_c_haines@btinternet.com>

libsemanage: Allow tmp files to be kept if a compile fails

---

libsepol/src/libsepol.map.in

Export the sepol_polcap_getnum/name() functions to users of
the shared library.  This will enable SETools to stop depending
on the static library.
Note that we may want to move polcaps.h up one level since
the convention is that headers directly under include/sepol are
shared library APIs while headers under include/sepol/policydb
are limited to static users.  However, this will unnecessarily
break the build for existing static users so it is deferred.
Suggested-by: Chris PeBenito <pebenito@ieee.org>
Signed-off-by: Stephen Smalley <sds@tycho.nsa.gov>

libsepol: Export sepol_polcap_getnum/name functions

---

libsemanage/src/direct_api.c

Fix sizeof calculation in array iteration introduced by commit
6bb8282c4cf66e93daa9684dbe9c75bb6b1e09a7
"libsemanage: replace access() checks to make setuid programs work"
Signed-off-by: Vit Mojzis <vmojzis@redhat.com>

libsemanage/direct_api.c: Fix iterating over array

---

checkpolicy/policy_define.c
libsepol/cil/src/cil_resolve_ast.c

This commit resolves conflicts in values of expandattribute statements
in policy language and expandtypeattribute in CIL.
For example, these statements resolve to false in policy language:
expandattribute hal_audio true;
expandattribute hal_audio false;
Similarly, in CIL these also resolve to false.
(expandtypeattribute (hal_audio) true)
(expandtypeattribute (hal_audio) false)
A warning will be issued on this conflict.
Motivation
When Android combines multiple .cil files from system.img and vendor.img
it's possible to have conflicting expandattribute statements.
This change deals with this scenario by resolving the value of the
corresponding expandtypeattribute to false. The rationale behind this
override is that true is used for reduce run-time lookups, while
false is used for tests …

Resolve conflicts in expandattribute.

---

python/sepolgen/src/sepolgen/refpolicy.py

This allows sepolgen to generate policy from AVC messages that contain
contexts translated by mcstrans.
Fixes:
\# echo "type=USER_AVC msg=audit(1468415802.940:2199604): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0-s15:c0.c1023 msg='avc:  denied  { status } for auid=n/a uid=0 gid=0 cmdline="/usr/lib/systemd/systemd-logind" scontext=system_u:system_r:systemd_logind_t:SystemLow-SystemHigh tcontext=system_u:system_r:init_t:s0-s15:c0.c1023 tclass=system  exe="/usr/lib/systemd/systemd" sauid=0 hostname=? addr=? terminal=?'" | audit2allow
libsepol.mls_from_string: invalid MLS context SystemLow-SystemHigh
libsepol.mls_from_string: could not construct mls context structure
libsepol.context_from_record: could not create context structure
libsepol.context_from_string: …

python/sepolgen: Try to translate SELinux contexts to raw

---

checkpolicy/checkmodule.c
checkpolicy/checkpolicy.c

Reduce noise when calling the checkpolicy command line. In Android, this
creates unnecessary build noise which we'd like to avoid.
https://en.wikipedia.org/wiki/Unix_philosophy
Rule of Silence
Developers should design programs so that they do not print
unnecessary output. This rule aims to allow other programs
and developers to pick out the information they need from a
program's output without having to parse verbosity.
An alternative approach would be to add a -s (silent) option to these
tools, or to have the Android build system redirect stdout to /dev/null.
Signed-off-by: Nick Kralevich <nnk@google.com>

checkpolicy: remove extraneous policy build noise

---

restorecond/restorecond.c

Since the default value of watch_file is set unconditionally *after* the
command-line arguments have been parsed, the -f option is (and has
always been) effectively ignored. Fix this by setting it before the
parsing.
Signed-off-by: Ondrej Mosnacek <omosnace@redhat.com>

restorecond: Do not ignore the -f option

---

libsemanage/utils/semanage_migrate_store

The selinux/semanage python module import error in semanage_migrate_store
was misleading. Before, it would report that the selinux/semanage modules
were not installed even though they were on the system.
Now the import failure is only reported if the modules are not installed.
Otherwise, a stack trace is printed for all other errors in the selinux/semanage
python modules.
Signed-off-by: Yuli Khodorkovskiy <yuli.khodorkovskiy@crunchydata.com>

libsemanage: improve semanage_migrate_store import failure

---

checkpolicy/checkpolicy.c
libsepol/include/sepol/policydb/policydb.h
libsepol/src/policydb.c

ocontexts (initial sids, fs_use_*, genfscon, portcon, etc) are sorted by libsemanage when using policy modules and by libsepol when using CIL, but they are not sorted by checkpolicy when creating a policy from a policy.conf.
Checkpolicy's behavior allows control over the ordering which determines the matching order for portcons and other ocontext rules, but there are times when that specific control is not desired.
This patch set exposes an internal ocontext sorting function and adds a command line option to checkpolicy to sort ocontexts.
James Carter (2):
libsepol: Create policydb_sort_ocontexts()
checkpolicy: Add option to sort ocontexts when creating a binary
policy
checkpolicy/checkpolicy.c                  | 22 +++++++++++++++++-----
libsepol/include/sepol/policydb/policydb.h |  2 ++ …

libsepol: Add ability to sort ocontexts in libsepol and add option to use it in checkpolicy

---

libsepol/src/kernel_to_cil.c
libsepol/src/kernel_to_common.c
libsepol/src/kernel_to_common.h
libsepol/src/kernel_to_conf.c
libsepol/src/module_to_cil.c

- Removes some redundent definitions of initial sid name strings
- Adds range checking when looking up an initial sid name string for an index
- Adds two new Xen initial sids
James Carter (4):
libsepol: Rename kernel_to_common.c stack functions
libsepol: Eliminate initial sid string definitions in module_to_cil.c
libsepol: Check that initial sid indexes are within the valid range
libsepol: Add two new Xen initial SIDs

libsepol: Cleanup initial sid handling when writing CIL and policy.conf files

---

libsepol/src/policydb.c

We need to convert from little-endian before dong range checks on the
ibpkey port numbers, otherwise we would be checking a wrong value.
Fixes: 9fbb3112769a ("libsepol: Add ibpkey ocontext handling")
Acked-by: William Roberts <william.c.roberts@intel.com>
Acked-by: Stephen Smalley <sds@tycho.nsa.gov>
Signed-off-by: Ondrej Mosnacek <omosnace@redhat.com>

libsepol: fix endianity in ibpkey range checks

---

mcstrans/src/mcstransd.c

There is a call to getpeercon_raw() in mcstransd, but nothing is done
with the context. The purpose of process_request() is to translate a
context and we would like that to succeed even if, for some reason,
getpeercon_raw() fails.
Signed-off-by: Yuli Khodorkovskiy <yuli@crunchydata.com>
Signed-off-by: Joshua Brindle <joshua.brindle@crunchydata.com>

mcstrans: remove unused getpeercon_raw() call

---

libselinux/src/label_file.c
libselinux/src/regex.c

load_mmap and regex_load_mmap (in the !USE_PCRE2 case) were
incorrectly treating the absence of any fixed stems or study data
as an error, rejecting valid file_contexts.bin files.  Remove
the extraneous validation checks.
Test:
$ cat > file_contexts <<EOF
(/.*)?                u:object_r:system_file:s0
/lib                   u:object_r:system_dir:s0
EOF
$ sefcontext_compile file_contexts
$ selabel_lookup -b file -k /lib -f file_contexts.bin
Before:
ERROR: selabel_open - Could not obtain handle.
After:
Default context: u:object_r:system_dir:s0
Reported-by: Jiyong Park <jiyong@google.com>
Signed-off-by: Stephen Smalley <sds@tycho.nsa.gov>

libselinux: fix overly strict validation of file_contexts.bin

---

scripts/run-flake8

When running flake8 on a directory, it does not analyze files without an
extension, like semanage_migrate_store, mlscolor-test, etc. Use grep to
find files with a Python shebang and build a list which is then given to
flake8.
This commit is possible now that some clean-up patches have been
applied, such as commit 69c56bd2f6e9 ("python/chcat: improve the code
readability") and b7227aaec1da ("mcstrans: fix Python linter warnings on
test scripts") and 3cb974d2d2a7 ("semanage_migrate_store: fix many
Python linter warnings").
Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>

scripts/run-flake8: run on Python scripts not ending with .py

---

libselinux/src/selinux_restorecon.c

When selinux_restorecon() is used to relabel symlinks, it performs the
following syscalls (as seen by running strace on restorecond):
lstat("/root/symlink", {st_mode=S_IFLNK|0777, st_size=6, ...}) = 0
statfs("/root/symlink", 0x7ffd6bb4d090) = -1 ENOENT (No such file or directory)
lstat("/root/symlink", {st_mode=S_IFLNK|0777, st_size=6, ...}) = 0
lgetxattr("/root/symlink", "security.selinux", "sysadm_u:object_r:user_home_t", 255) = 30
The second one triggers a SELinux check for lnk_file:read, as statfs()
dereferences symbolic links. This call to statfs() is only used to find
out whether "restoreconlast" xattr can be ignored, which is always the
case for non-directory files (the first syscall, lstat(), is actually
used to perform this check).
Skip the call to statfs() when setrestoreconlast …

libselinux: do not dereference symlink with statfs in selinux_restorecon

---

libselinux/utils/avcstat.c
libselinux/utils/compute_av.c
libselinux/utils/compute_create.c
libselinux/utils/compute_member.c
libselinux/utils/compute_relabel.c
libselinux/utils/compute_user.c
libselinux/utils/getfilecon.c
libselinux/utils/getpidcon.c
libselinux/utils/getseuser.c
libselinux/utils/policyvers.c
libselinux/utils/setfilecon.c

Another trivial patch to improve code readability. I did not replace exit(1) with EXIT_FAILURE, because some of the code uses exit(2), exit(3) etc, so preferred to keep the raw integers there.

Global replace exit(0) with more readable exit(EXIT_SUCCESS)

---

libsepol/src/kernel_to_conf.c

8292fce32195  libsepol: Replace constant with sizeof()
bd396fb2216d libsepol: Check strdup() failures

libsepol fixes

---

libsepol/cil/src/cil_verify.c

Installing a cil module with invalid mlsconstrain syntax currently
results in a segfault. In the following module, the right-hand side of
the second operand of the OR is a list (mlstrustedobject):
$ cat test.cil
(class test (foo) )
(classorder (unordered test))
(mlsconstrain (test (foo))
(or
(dom h1 h2)
(eq t2 (mlstrustedobject))
)
)
$ sudo semodule -i test.cil
zsh: segmentation fault  sudo semodule -i test.cil
This syntax is invalid and should error accordingly, rather than
segfaulting. This patch provides this syntax error for the same module:
$ sudo semodule -i test.cil
t1, t2, r1, r2, u1, u2 cannot be used on the left side with a list on the right side
Bad expression tree for constraint
Bad constrain declaration at /var/lib/selinux/mls/tmp/modules/400/test/cil:4
semodule:  Failed! …

libsepol/cil: fix mlsconstrain segfault

---

checkpolicy/checkpolicy.8
checkpolicy/checkpolicy.c
libsemanage/man/man5/semanage.conf.5
libsemanage/src/conf-parse.y
libsemanage/src/conf-scan.l
libsemanage/src/direct_api.c
libsemanage/src/semanage_conf.h
libsepol/include/sepol/policydb.h
libsepol/include/sepol/policydb/policydb.h
libsepol/src/libsepol.map.in
libsepol/src/optimize.c
libsepol/src/policydb_public.c
secilc/secilc.8.xml
secilc/secilc.c

Changes in v4:
* fix deallocation in error path in build_type_map()
* fix leaked cond nodes
* also update the man pages
* use UINT32_C for 0xFFFFFFFF constant
* squash in the RFC patches & drop the semodule patch
v3: https://lore.kernel.org/selinux/20190529073759.20548-1-omosnace@redhat.com/T/
Changes in v3:
* fix bad patch squashing
* rename secilc --optimize-policy option to --optimize (to be simpler
and consistent with checkpolicy and semodule)
v2: https://lore.kernel.org/selinux/20190528145912.13827-1-omosnace@redhat.com/T/
Changes in v2:
* fix handling of dontaudit (AVTAB_DENY) rules
* switch optimization from opt-out to opt-in everywhere
* add a patch from jwcart2 that adds optimization support to
checkpolicy as well
* add two RFC modifications (see log messages for details):
* one …

Remove redundant rules when building policydb

---

lgtm.yml

Add a configuration file in order to parse the C code on
https://lgtm.com/projects/g/SELinuxProject/selinux/
The documentation about this file is on
https://help.semmle.com/lgtm-enterprise/user/help/lgtm.yml-configuration-file.html
and
https://help.semmle.com/lgtm-enterprise/user/help/cpp-extraction.html
Fixes: https://github.com/SELinuxProject/selinux/issues/98
Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>

Add configuration file for lgtm.com

---

libsepol/cil/src/cil.c

Acked-by: Ondrej Mosnacek <omosnace@redhat.com>
Signed-off-by: William Roberts <william.c.roberts@intel.com>

cil: drop remaining dso.h include

---

libselinux/utils/Makefile

Currently, the src/Makefile provides the FTS_LDLIBS when building against musl
or uClibc. However, this is missing from utils/Makefile, which causes linking
to fail.
Add the FTS_LDLIBS variable to the LDLIBS variable in utils/Makefile to fix
compiling against uClibc and musl.
Signed-off-by: Adam Duskett <Aduskett@gmail.com>

Fix building against musl and uClibc libc libraries.

---

libselinux/include/selinux/selinux.h

Follow-up of: 9eb9c9327563014ad6a807814e7975424642d5b9 ("Get rid of security_context_t and fix const declarations.")
Signed-off-by: Christian Göttsche <cgzones@googlemail.com>

libselinux: mark security_context_t typedef as deprecated

---

scripts/ci/fedora-test-runner.sh

git log -1 may use a pager to output long messages, and when the pager
is invoked, leads to stalls on the ci system waiting for user input.
Use --oneline to print the short part of the commit message and
the digest. This information is for debug/informational purposes only,
so truncating the output is sufficient.
Reported-by: Stephen Smalley <sds@tycho.nsa.gov>
Signed-off-by: William Roberts <william.c.roberts@intel.com>

ci: fix stall on git log -1
